version: 1.0.0
file_location: ..\..\..\..\Documents\ws_traduction\MSH_INTERNATIONAL_French _With_Separator.xls
database:
    driver:  pdo_mysql
    charset: utf8
    host: 127.0.0.1
    dbname: silex_api
    user: root
    password: password